### ISSUE TITLE
Question about landing page as html

### ISSUE THREAD

**Issue by tschaub** [opengeospatial/ets-ogcapi-features-1.0#53]
[The docs](https://github.com/opengeospatial/ets-wfs30/blob/758ffaf536978fa34a0eb907147ad467072850b2/src/site/asciidoc/index.adoc) for this repo say
> The landing page must support HTML as output format.

My reading of the spec is that [`html` is recommended](http://docs.opengeospatial.org/DRAFTS/17-069.html#rec_html) but not required.

Do these tests require that a service implements the `html` encoding?  If so, what requirement in the spec does that relate to?

**Comment by dstenger** [comment]
Yes, you are right.
This is a requirement of the test suite but it is recommended by spec.

However, due to technical limitations we had to define a couple of preconditions services must fulfil to be able to use this test suite.

The HTML encoding is just related to the landing page. Otherwise, JSON encoding must be supported by tested service.

If this precondition prevents that you can use this test suite, can you please describe your problem in detail?

**Comment by dstenger** [comment]
We just rechecked the implementation of test suite and actually HTML is not mandatory for the landing page (also tested it).
Thus, I created a pull request correcting documentation. In addition, the wording of test suite preconditions was improved.
